server:
  port: 8080

spring:
  data:
    mongodb:
      database: CuberReality
      host: 10.122.0.2
      port: 27017
      username: nearbysecuber
      password: Kuchkitho420

constants:
  access_token_validity_seconds: 31104000
  signing_key: kuchkitho
  token_prefix: Bearer
  header_string: Authorization
  authorities_key: scopes
  otp_len: 6
  twilio_account_sid: xxxxxxxxxx
  twilio_auth_token: xxxxxxxxxx
  twilio_register_phone_number: +17865634883
  opt_provider_primary: exotel
  exotel_account_sid: cuberreality1
  exotel_account_user: xxxxxxxxxx
  exotel_auth_token: xxxxxxxxxx
  exotel_register_phone_number: CBRLTY
  reseller_notification_server_key: xxxxxxxxxx
  soft_app_update_version: 4200
  hard_app_update_version: 4100
  crm_refresh_token: xxxxxxxxxx
  crm_client_id: xxxxxxxxxx
  crm_client_secret: xxxxxxxxxx
  crm_base_url: https://www.zohoapis.in
  crm_auth_base_url: https://accounts.zoho.in
  bearer_token: xxxxxxxxxx

