server:
    port: 8000

constants:
  access_token_validity_seconds: 31104000
  signing_key: kuchkitho
  token_prefix: Bearer
  header_string: Authorization
  authorities_key: scopes
  otp_len: 6
  account_sid: ACa38280a59b0f0c453ea1a84dceb8ea48
  auth_token: 8d6f7eb833c7d9344d92ea36dc9161e2
  register_phone_number: +16787261905
  reseller_notification_server_key: key=AAAAtwOmtzc:APA91bHAOpuP8ubYFtwoQpOzLFZyLe1VjFqipyBAqPc3-DIA8XGKnj223TUXtMPIKTtvAUObVaLkuF80VPPYGchGzvC9pM4tvMZ1zC2TTZawh6pQhN9CUHRx0J4lOzm9PZFS_E2-m_1s
  reseller_app_version: 4200
  crm_refresh_token: 1000.90ee9177932cdfc3e741b2529b7993e4.5b99c635844a4cd1d1b9713084038b88
  crm_client_id: 1000.DJ1HFBUXXQ8YQUO4CH5KL5PB2KPZAM
  crm_client_secret: 694014c68fdff36d4cae0d420b581e700f1f88b5daxxxx
  crm_base_url: https://accounts.zoho.in

